# Generated by Django 4.0.1 on 2022-03-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costumername', models.CharField(max_length=50)),
                ('productname', models.CharField(max_length=50)),
                ('productprice', models.FloatField()),
                ('productdetails', models.CharField(max_length=1000)),
                ('productimage', models.CharField(default='some string', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='order_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(default='Not Available', max_length=50)),
                ('cname', models.CharField(default='Not Available', max_length=50)),
                ('contry', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=500)),
                ('apartment', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(default='Not Available', max_length=50)),
                ('productname', models.CharField(default='Not Available', max_length=50)),
                ('productprice', models.IntegerField(default=0)),
                ('productimage', models.CharField(default='Not Available', max_length=5000)),
                ('shipping_methode', models.CharField(default='Not Available', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('Stock', models.IntegerField()),
                ('image', models.CharField(max_length=5000)),
                ('detail', models.CharField(default='sume string', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
