# Generated by Django 4.0.1 on 2022-03-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='productdetails',
            field=models.CharField(default='Not available', max_length=500),
        ),
    ]
