# Generated by Django 4.0.1 on 2022-03-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order_list_productdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='productprice',
            field=models.FloatField(default=0),
        ),
    ]
