# Generated by Django 4.0.1 on 2022-03-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.CharField(default='sume string', max_length=1000),
        ),
    ]
