# Generated by Django 4.0.1 on 2022-04-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_order_list_productprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='cname',
            field=models.CharField(default='Not Available', max_length=500),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='email',
            field=models.CharField(default='Not Available', max_length=500),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='fname',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='lname',
            field=models.CharField(default='Not Available', max_length=500),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='productdetails',
            field=models.CharField(default='Not available', max_length=5000),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='productname',
            field=models.CharField(default='Not Available', max_length=5000),
        ),
    ]
