# Generated by Django 4.0.1 on 2022-03-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costumername', models.CharField(max_length=50)),
                ('productname', models.CharField(max_length=50)),
                ('productprice', models.IntegerField()),
                ('productdetails', models.CharField(max_length=1000)),
            ],
        ),
    ]
