# Generated by Django 4.0.1 on 2022-04-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_order_list_cname_alter_order_list_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='productdetails',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='cart',
            name='productimage',
            field=models.CharField(default='some string', max_length=500),
        ),
        migrations.AlterField(
            model_name='cart',
            name='productname',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='productimage',
            field=models.CharField(default='Not Available', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.CharField(default='sume string', max_length=5000),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
