# Generated by Django 4.0.1 on 2022-03-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_cart_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='productimage',
            field=models.CharField(default='some string', max_length=5000),
        ),
    ]
